---

services:
  - docker

language: python
python:
  - 2.7

install:
  - pip install -r dev-requirements.txt
  - pip install -e .
script:
  - cd tests/helpers && make up
  - cd ../.. && py.test -v
#  - pylama .
